version: '3'
services:

  jinux2:

    image: ${DOCKER_USER_ID}/jinux-assignment4:${BUILD_NUMBER}
    container_name: jinux
    build:
      context: .

  production:
    image: ${DOCKER_USER_ID}/jinux-assignment4:${BUILD_NUMBER}
    restart: always
    ports:
      - 80:80

